### ISSUE TITLE
Trouble getting loci2phylip and loci2fasta to work

### ISSUE THREAD

**Issue by alx552** [btmartin721/file_converters#1]
hello,  
I have been trying to get each locus as a phylip or fasta for use as inputs for RAxML. When I run : 

python3.5 loci2phylip.py --loci ipy002-noTess-reducedBrise_min50perc.loci 

I get an error (I am not sure what it means):

Traceback (most recent call last):
  File "loci2phylip.py", line 81, in <module>
    for aln, lcount, icount, slen in locusGenerator(fin, locus_num):
  File "loci2phylip.py", line 43, in locusGenerator
    yield locus, locus_count, ind_count, seq_len
UnboundLocalError: local variable 'seq_len' referenced before assignment

when I tried the same file for loci2fasta it produced empty fasta files.

do you know what could be the issue?

**Comment by btmartin721** [comment]
Hello Alex,

Sorry for the issue. I will look into this. I certainly want the scripts and packages on my GitHub to be accessible and use-able. It might be tomorrow or Monday before I can figure out what the problem might be.

**Comment by btmartin721** [comment]
I ran both loci2phylip and loci2fasta, and they both worked for me. Perhaps the bug is due your system being setup different than mine, or something to do with the file. Could you please send me the .loci file? Or, if you don't want to send me the whole thing, could you just send me the first four loci in the file? Doing so will allow me to better debug it. You can attach it here, or send it to btm002@email.uark.edu 

Also, did pyRAD produce the .loci file? Or have you filtered it in any way?

Thanks,

-Bradley

**Comment by alx552** [comment]
Hi Bradley, 
I uploaded the script and file to a computing cluster and got the same error so I suspect it may be the file. I got the file directly from ipyrad v0.7.26 and used pythonv3.6 to run the script.  I have attached the file containing the first three loci (saved as .txt due to github requirements). 
[test-3loci-ipy002.loci.txt](https://github.com/btmartin721/file_converters/files/2546235/test-3loci-ipy002.loci.txt)

**Comment by btmartin721** [comment]
Hi Alex. I fixed the issue. It turns out that ipyrad .loci files have a slightly different format than the old regular pyRAD v. 3.66. The samples names for the old pyRAD loci files have a ">" character preceding each sample ID (just like FASTA files), but the ipyrad .loci files do not have the ">" character before the sample IDs. So I fixed my code for both loci2phylip and loci2fasta to be compatible with both old pyRAD and the new ipyrad loci files. Thanks for reporting this issue. I hope it helps.

-Bradley
